# Generated by Django 5.0.7 on 2024-07-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', '-created_at']},
        ),
    ]
